all: ibmcmd.com \
     ibmdos.com ibmbio.com asm.com hex2bin.com xtrans.com hello.com \
     mem.com cls.com

ibmbio.com: ibmbio.exe
	echo 60|bin\exe2bin.exe ibmbio.exe ibmbio.com

ibmbio.exe: ibmbio.obj
	bin\link.exe ibmbio,ibmbio,ibmbio,ibmbio,

ibmbio.obj: ibmbio.asm 
	bin\masm.exe ibmbio,ibmbio,ibmbio,ibmbio

ibmdos.com: ibmdos.exe
	bin\exe2bin.exe ibmdos.exe ibmdos.com

ibmdos.exe: ibmdos.obj
	bin\link.exe ibmdos,ibmdos,ibmdos,ibmdos,

ibmdos.obj: ibmdos.asm dos.asm
	bin\masm.exe ibmdos,ibmdos,ibmdos,ibmdos

ibmcmd.com: ibmcmd.exe 
	bin\exe2bin.exe ibmcmd.exe ibmcmd.com

ibmcmd.exe: ibmcmd.obj
	bin\link.exe ibmcmd,ibmcmd,ibmcmd,ibmcmd,

ibmcmd.obj: ibmcmd.asm command.asm
	bin\masm.exe ibmcmd,ibmcmd,ibmcmd,ibmcmd

mem.com: mem.exe
	bin\exe2bin.exe mem.exe mem.com

mem.exe: mem.obj
	bin\link.exe mem,mem,mem,mem, 

mem.obj: mem.asm
	bin\masm.exe mem,mem,mem,mem

cls.com: cls.exe
	bin\exe2bin.exe cls.exe cls.com

cls.exe: cls.obj
	bin\link.exe cls,cls,cls,cls, 

cls.obj: cls.asm
	bin\masm.exe cls,cls,cls,cls

hello.com: hello.asm asm.com hex2bin.com
	asm.com hello.  z
	hex2bin.com hello

xtrans.com: trans.asm asm.com hex2bin.com
	asm.com trans.  z
	hex2bin.com trans

asm.com: asm.asm
	bin\asm.com asm.  z
	bin\hex2bin.com asm

hex2bin.com: hex2bin.asm
	bin\asm.com hex2bin.  z
	bin\hex2bin.com hex2bin

clean:
	del *.com
	del *.exe
	del *.obj
	del *.crf
	del *.err
	del *.lst
	del *.map
	del *.hex
	del *.prn
	del *.log

