all: ibmcmdex.com ibmcmd.com 
	    
ibmcmd.com: ibmcmd.exe
	bin\exe2bin.exe ibmcmd.exe ibmcmd.com

ibmcmd.exe: ibmcmd.obj
	bin\link.exe ibmcmd,ibmcmd,ibmcmd,ibmcmd,

ibmcmd.obj: ibmcmd.asm
	bin\masm.exe ibmcmd,ibmcmd,ibmcmd,ibmcmd 

ibmcmdex.com: ibmcmdex.exe
	bin\exe2bin.exe ibmcmdex.exe ibmcmdex.com

ibmcmdex.exe: ibmcmdex.obj
	bin\link.exe ibmcmdex,ibmcmdex,ibmcmdex,ibmcmdex,

ibmcmdex.obj: ibmcmdex.asm
	bin\masm.exe ibmcmdex,ibmcmdex,ibmcmdex,ibmcmdex

clean:
	del ibmcmd.exe 
	del ibmcmd.obj 
	del ibmcmd.com
	del ibmcmdex.exe 
	del ibmcmdex.obj 
	del ibmcmdex.com
	del *.crf 
	del *.err 
	del *.lst 
	del *.map
